name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'Install Packages'
        run: 'npm install'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          VUE_APP_API_URL: https://backend.pro.tabeazy.com/seller/connector/
        run: npm run electron:build
      
      - name: Check Dir
        run: ls ./electron_dist/

